'use strict';
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const previews={health:{index:'01',url:'project1.html',title:'Uninsured population',unit:'%',max:40,rows:[['Tukwila',34],['Federal Way',32],['Rainier Valley',22],['Northgate',14],['Bellevue',6]]},mental:{index:'02',url:'project2.html',title:'Behavioral health facilities · sample',unit:'',max:40,rows:[['Seattle Core',38],['Bellevue',14],['Northgate',6],['Rainier Valley',3],['Tukwila',1]]},food:{index:'03',url:'project3.html',title:'Distance to supermarket · sample',unit:' mi',max:2.5,rows:[['Skyway',2.1],['White Center',1.6],['Delridge',1.4],['Northgate',0.7],['Bellevue',0.4]]}};
const num=n=>Number(n).toLocaleString('en-US');
function chartRows(rows,max,unit='',selected=''){return `<div class="bar-chart">${rows.map(([name,value,key])=>`<div class="bar-row ${key===selected?'selected':''}"><span>${esc(name)}</span><div class="bar-track"><i style="--width:${value===null?0:Math.min(100,value/max*100)}%"></i></div><strong>${value===null?'N/A':num(value)+unit}</strong></div>`).join('')}</div>`;}
function metric(label,value,note,word=false){return `<div><span>${label}</span><strong${word?' class="word-metric"':''}>${value}</strong><small>${note}</small></div>`;}
function lookupZip(zip){
 const result=$('#zip-result');if(!result)return;
 const d=window.PORTFOLIO_ZIPS[zip];
 $$('[data-zip]').forEach(b=>{b.classList.toggle('active',b.dataset.zip===zip);b.setAttribute('aria-pressed',String(b.dataset.zip===zip))});
 if(!d){result.innerHTML=`<div class="no-result"><h3>No scenario for ${esc(zip || 'this ZIP code')}.</h3><p>This prototype includes ${Object.keys(window.PORTFOLIO_ZIPS).length} ZIP codes. Try a neighborhood above. A missing record does not imply that an area is outside King County or lacks services.</p></div>`;return;}
 const rows=['98188','98003','98118','98125','98004'].map(z=>[window.PORTFOLIO_ZIPS[z].name.split(' / ')[0].replace(' Core',''),parseFloat(window.PORTFOLIO_ZIPS[z].uninsured),z]);
 if(!rows.some(r=>r[2]===zip))rows.push([d.name,parseFloat(d.uninsured),zip]);
 result.innerHTML=`<div class="result-heading"><div><h3>${esc(d.name)}</h3><p>ZIP ${esc(zip)} · ${esc(d.pop)} residents in sample</p></div><span>SCENARIO</span></div><div class="result-metrics">${metric('Uninsured population',esc(d.uninsured),'Illustrative percentage')}${metric('Refugee-serving clinics',num(d.clinics),'Unverified sample count')}${metric('Record geography',esc(zip),'ZIP code scenario')}</div><div class="tool-chart"><div class="chart-heading"><span>Uninsured population · sample comparison</span><span>0–40%</span></div>${chartRows(rows,40,'%',zip)}</div>`;
}
if($('#zip-form')){$('#zip-form').addEventListener('submit',e=>{e.preventDefault();lookupZip($('#zip-input').value.trim())});$$('[data-zip]').forEach(b=>b.addEventListener('click',()=>{$('#zip-input').value=b.dataset.zip;lookupZip(b.dataset.zip)}));lookupZip('98003');}
const areas={
 'federal-way':{name:'Federal Way',population:93000,facilities:0},tukwila:{name:'Tukwila',population:21000,facilities:1},rainier:{name:'Rainier Valley',population:46000,facilities:3},northgate:{name:'Northgate',population:32000,facilities:6},bellevue:{name:'Bellevue',population:156000,facilities:14},seattle:{name:'Seattle Core',population:320000,facilities:38}
};
function residentsPerFacility(population,facilities){return facilities>0?Math.round(population/facilities):null;}
function selectArea(key){const d=areas[key];if(!d||!$('#provider-result'))return;const ratio=residentsPerFacility(d.population,d.facilities);
 $$('[data-area]').forEach(b=>{b.classList.toggle('active',b.dataset.area===key);b.setAttribute('aria-pressed',String(b.dataset.area===key))});
 $('#provider-result').innerHTML=`<div class="result-heading"><div><h3>${d.name}</h3><p>Population and facility counts from the original prototype</p></div><span>SCENARIO</span></div><div class="result-metrics">${metric('Population',num(d.population),'Illustrative population')}${metric('Behavioral health facilities',num(d.facilities),'Facilities, not clinicians')}${metric('Residents per facility',ratio===null?'Not defined':num(ratio),ratio===null?'Cannot divide by zero facilities':num(d.population)+' ÷ '+num(d.facilities)+' facilities',ratio===null)}</div>`;
 const rows=Object.entries(areas).map(([k,a])=>[a.name,residentsPerFacility(a.population,a.facilities),k]).sort((a,b)=>(a[1]??Infinity)-(b[1]??Infinity));
 $('#provider-chart').innerHTML=chartRows(rows,25000,'',key)+`<p class="comparison-explanation">Federal Way’s sample has zero facilities, so its ratio is not defined. Bars compare illustrative scenarios and do not establish a shortage designation.</p>`;
}
if($('#provider-result')){$$('[data-area]').forEach(b=>b.addEventListener('click',()=>selectArea(b.dataset.area)));selectArea('bellevue');}
const foods={
 '98178':{name:'Skyway',stores:1,distance:2.1,diabetes:14.2,obesity:31.4,poverty:26},'98146':{name:'White Center',stores:2,distance:1.6,diabetes:13.8,obesity:30.2,poverty:24},'98106':{name:'Delridge',stores:2,distance:1.4,diabetes:12.6,obesity:28.7,poverty:20},'98125':{name:'Northgate',stores:6,distance:.7,diabetes:9.8,obesity:22.1,poverty:12},'98004':{name:'Bellevue',stores:12,distance:.4,diabetes:7.4,obesity:19.1,poverty:5.8},'98103':{name:'Fremont',stores:9,distance:.5,diabetes:7.9,obesity:20.4,poverty:7.1}
};
function difference(a,b){return Math.round((a-b)*10)/10;}
function renderFood(){const ak=$('#left-area').value,bk=$('#right-area').value,a=foods[ak],b=foods[bk];const metrics=[['Grocery stores','stores','',''],['Supermarket distance','distance',' mi',' mi'],['Diabetes','diabetes','%',' pp'],['Obesity','obesity','%',' pp'],['Poverty','poverty','%',' pp']];
 $('#food-result').innerHTML=`${ak===bk?'<p class="compare-same">Same neighborhood selected. Every difference is zero.</p>':''}<table class="comparison-table"><caption>Illustrative neighborhood comparison · difference = A minus B</caption><thead><tr><th scope="col">Metric</th><th scope="col">${a.name}<br><small>${ak} · A</small></th><th scope="col">${b.name}<br><small>${bk} · B</small></th><th scope="col">Difference</th></tr></thead><tbody>${metrics.map(([label,key,unit,deltaUnit])=>{const d=difference(a[key],b[key]);return `<tr><th scope="row">${label}</th><td>${a[key]}${unit}</td><td>${b[key]}${unit}</td><td>${d>0?'+':''}${d}${deltaUnit}</td></tr>`}).join('')}</tbody></table><p class="comparison-explanation">pp = percentage points. A positive difference means the value for ${a.name} is higher; it does not by itself indicate better access or a causal relationship.</p>`;
}
if($('#food-result')){['left','right'].forEach(side=>{const sel=$('#'+side+'-area');sel.innerHTML=Object.entries(foods).map(([k,d])=>`<option value="${k}">${d.name} · ${k}</option>`).join('');sel.value=side==='left'?'98178':'98004';sel.addEventListener('change',renderFood)});renderFood();}
const censusUrl='https://api.census.gov/data/2022/acs/acs1/profile?get=NAME,DP03_0099PE,DP03_0128PE,DP02_0094PE,DP03_0074PE&for=county:033&in=state:53';
function cdcUrl(measure){return 'https://data.cdc.gov/resource/swc5-untb.json?locationid=53033&datavaluetypeid=CrdPrv&measureid='+encodeURIComponent(measure);}
async function getJSON(url){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(url,{signal:controller.signal});if(!r.ok)throw new Error('Source unavailable');const body=await r.text();if(body.includes('<title>Missing Key</title>'))throw new Error('Census API key required');return JSON.parse(body);}finally{clearTimeout(timeout);}}
function percentage(raw){if(raw===null||raw===undefined||raw==='')throw new Error('Missing value');const value=Number(raw);if(!Number.isFinite(value)||value<0||value>100)throw new Error('Invalid percentage');return value;}
async function getCensus(){const data=await getJSON(censusUrl);if(!Array.isArray(data)||!Array.isArray(data[0]))throw new Error('Invalid Census response');const row=data.slice(1).find(r=>r[data[0].indexOf('state')]==='53'&&r[data[0].indexOf('county')]==='033');if(!row)throw new Error('County not found');return Object.fromEntries(data[0].map((k,i)=>[k,row[i]]));}
async function getCDC(measure){const data=await getJSON(cdcUrl(measure));if(!Array.isArray(data))throw new Error('Invalid CDC response');const row=data.filter(r=>r.locationid==='53033'&&r.datavaluetypeid==='CrdPrv'&&r.measureid===measure).sort((a,b)=>Number(b.year)-Number(a.year))[0];if(!row)throw new Error('County not found');return {value:percentage(row.data_value),year:row.year,low:percentage(row.low_confidence_limit),high:percentage(row.high_confidence_limit)};}
async function loadContext(panel){const type=panel.dataset.context,button=$('.refresh-data',panel);button.disabled=true;$('.fetch-status',panel).textContent='Connecting to public data sources…';
 const configs={health:[['Uninsured adults · ages 18–64','cdc','ACCESS2'],['Routine checkup in past year · adults','cdc','CHECKUP'],['Dental visit in past year · adults','cdc','DENTAL']],mental:[['Frequent mental distress · adults','cdc','MHLTH'],['Depression prevalence · adults','cdc','DEPRESSION'],['Uninsured adults · ages 18–64','cdc','ACCESS2']],food:[['Diabetes prevalence · adults','cdc','DIABETES'],['Obesity prevalence · adults','cdc','OBESITY'],['High blood pressure · adults','cdc','BPHIGH']]};
 const metrics=configs[type];$('.context-grid',panel).innerHTML=metrics.map(([label])=>`<div class="context-metric"><span>${label}</span><strong>—</strong><small>Loading King County estimate…</small></div>`).join('');
 const censusPromise=getCensus().then(c=>{const fields=type==='food'?[['Households receiving SNAP','DP03_0074PE'],['Below poverty line','DP03_0128PE']]:[['Uninsured civilian population','DP03_0099PE'],['Below poverty line','DP03_0128PE'],['Foreign-born population','DP02_0094PE']];$('.census-content',panel).innerHTML='<p>ACS 2022 · King County · Historical one-year estimates</p>'+fields.map(([label,key])=>`<p>${label}: <strong>${percentage(c[key]).toFixed(1)}%</strong></p>`).join('');return c;}).catch(e=>{$('.census-content',panel).innerHTML=`<p>${e.message==='Census API key required'?'The Census API currently requires an API key for this request.':'The Census API did not return a usable response.'} Supplemental Census estimates are unavailable; no demo values have been substituted. CDC indicators above remain a separate source.</p>`;return null;});
 const results=await Promise.allSettled(metrics.map(async([label,source,key])=>{if(source==='census'){const c=await censusPromise;return{label,value:percentage(c[key]),note:'ACS 2022 · King County, WA',detail:key==='DP03_0099PE'?'Civilian noninstitutionalized population':'Historical one-year estimate'};}const d=await getCDC(key);return {label,value:d.value,note:'CDC PLACES · '+d.year+' · King County',detail:'Crude prevalence · 95% CI '+d.low+'–'+d.high+'%'};}));
 let success=0;$('.context-grid',panel).innerHTML=results.map((r,i)=>{if(r.status==='rejected')return `<div class="context-metric"><span>${metrics[i][0]}</span><strong class="unavailable">Unavailable</strong><small>Public source did not return a usable estimate. No fallback substituted.</small></div>`;success++;const d=r.value;return `<div class="context-metric"><span>${d.label}</span><strong>${d.value.toFixed(1)}%</strong><small>${esc(d.note)}<br>${esc(d.detail)}</small></div>`;}).join('');
 $('.fetch-status',panel).textContent=success?'Retrieved '+success+' of '+metrics.length+' indicators · '+new Date().toLocaleString()+' · Observation years shown above.':'Public data could not be retrieved. You can still explore the labeled scenarios above, or retry.';
 $('.context-source-links',panel).innerHTML=`<a href="${esc(censusUrl)}" target="_blank" rel="noopener noreferrer">Census API response ↗</a>`+metrics.filter(m=>m[1]==='cdc').map(([label,,key])=>`<a href="${esc(cdcUrl(key))}" target="_blank" rel="noopener noreferrer">${label} source ↗</a>`).join('');await censusPromise;button.disabled=false;
}
$$('[data-context]').forEach(panel=>{$('.refresh-data',panel).addEventListener('click',()=>loadContext(panel));loadContext(panel);});
$$('[data-preview]').forEach(button=>button.addEventListener('click',()=>{const p=previews[button.dataset.preview];$$('[data-preview]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',b===button?'true':'false')});$('#preview-index').textContent=p.index;$('#preview-link').href=p.url;$('#preview-link').setAttribute('aria-label','Open '+button.textContent+' case study');$('#preview-chart').innerHTML=`<div class="chart-heading"><span>${p.title}</span><span>${p.unit}</span></div><div class="bar-chart">${p.rows.map(([n,v])=>`<div class="bar-row"><span>${n}</span><div class="bar-track"><i style="--width:${v/p.max*100}%"></i></div><strong>${v}${p.unit}</strong></div>`).join('')}</div><div class="chart-axis"><span>0</span><span>${p.max/2}</span><span>${p.max}${p.unit}</span></div>`}));
