'use strict';
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const median=values=>{const a=[...values].sort((a,b)=>a-b);return a.length?(a[Math.floor((a.length-1)/2)]+a[Math.floor(a.length/2)])/2:null;};
let data,filtered=[],status='',pageIndex=0;const pageSize=15;
function age(record){return record.applied?Math.floor((Date.parse(data.meta.asOfDate)-Date.parse(record.applied))/86400000):null;}
function render(){
 const type=$('type').value,year=$('year').value,query=$('search').value.trim().toLowerCase(),threshold=Math.max(0,Number($('threshold').value)||0);
 filtered=data.records.filter(r=>(!type||r.type===type)&&(!year||r.applied?.startsWith(year))&&(!query||r.id.toLowerCase().includes(query))&&(!status||r.status===status));
 const intervals=filtered.map(r=>r.daysToIssue).filter(n=>n!==null&&n>=0),med=median(intervals);
 const review=filtered.filter(r=>r.status!=='Issued'&&age(r)!==null&&age(r)>threshold).length;
 const pages=Math.max(1,Math.ceil(filtered.length/pageSize));pageIndex=Math.min(pageIndex,pages-1);
 $('status').innerHTML=['',...data.statusSummary.map(s=>s.status)].map(s=>`<button data-status="${esc(s)}" aria-pressed="${status===s}">${esc(s||'All statuses')}</button>`).join('');
 $('permit-output').innerHTML=`<div class="metrics"><div class="metric"><b>${filtered.length.toLocaleString()}</b><span>Matching active-layer records</span></div><div class="metric"><b>${med===null?'—':`${med.toFixed(1)}d`}</b><span>Median application → issue · ${intervals.length} valid intervals</span></div><div class="metric"><b>${review}</b><span>Non-issued cases older than ${threshold} calendar days</span></div></div><div class="table-wrap" tabindex="0" role="region" aria-label="Scrollable results table"><table><thead><tr><th>Permit / inspect</th><th>Type</th><th>Status</th><th>Applied</th><th>Calendar age</th><th>Review marker</th></tr></thead><tbody>${filtered.slice(pageIndex*pageSize,(pageIndex+1)*pageSize).map(r=>`<tr><td><button class="small-button" data-record="${esc(r.id)}">${esc(r.id)} ↗</button></td><td>${esc(r.type.replace('BLD-',''))}</td><td><span class="pill">${esc(r.status)}</span></td><td>${esc(r.applied||'Not recorded')}</td><td>${age(r)===null?'—':age(r)+'d'}</td><td>${r.status!=='Issued'&&age(r)!==null&&age(r)>threshold?'Review candidate':'—'}</td></tr>`).join('')||'<tr><td colspan="6">No records match. Try a different filter or permit number.</td></tr>'}</tbody></table></div>`;
 $('page-label').textContent=`Page ${pageIndex+1} of ${pages} · ${filtered.length.toLocaleString()} records · snapshot as of ${data.meta.asOfDate}`;$('prev').disabled=pageIndex===0;$('next').disabled=pageIndex>=pages-1;
 document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{status=b.dataset.status;pageIndex=0;render();document.querySelector(`[data-status="${status}"]`).focus();});
 document.querySelectorAll('[data-record]').forEach(b=>b.onclick=()=>{const r=data.records.find(r=>r.id===b.dataset.record);$('detail-body').innerHTML=`<h3>${esc(r.id)}</h3><p>${esc(r.type)} · ${esc(r.status)}</p>${[['Applied',r.applied],['Issued',r.issued],['Expires',r.expires],['Finalized',r.finalized]].map(([label,date])=>`<div class="milestone"><b>${label}</b>${esc(date||'Not recorded in this snapshot')}</div>`).join('')}<p class="note">Work class: ${esc(r.workClass||'Not recorded')}<br>Category: ${esc(r.category||'Not recorded')}<br>No intermediate review history is supplied by this snapshot.</p>`;$('detail').showModal();});
}
fetch('datasets/permits.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{data=d;for(const [id,values] of [['type',[...new Set(d.records.map(r=>r.type))].sort()],['year',[...new Set(d.records.filter(r=>r.applied).map(r=>r.applied.slice(0,4)))].sort().reverse()]])values.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;$(id).append(o);});['type','year','search','threshold'].forEach(id=>$(id).addEventListener('input',()=>{pageIndex=0;render();}));$('prev').onclick=()=>{pageIndex--;render();};$('next').onclick=()=>{pageIndex++;render();};$('close').onclick=()=>$('detail').close();$('export').onclick=()=>{const fields=['id','type','status','applied','issued','daysToIssue'];const csv=[fields.join(','),...filtered.map(r=>fields.map(k=>'"'+String(r[k]??'').replace(/"/g,'""')+'"').join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='renton-active-permits-filtered.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};render();window.dispatchEvent(new Event('portfolio:ready'));}).catch(()=>$('permit-output').innerHTML='<p class="error">The permit snapshot could not load. Reload this page or download the data below.</p>');
