'use strict';
const $ = id => document.getElementById(id);
const escapeText = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const median = values => { const a = [...values].sort((a,b)=>a-b); return a.length ? (a[Math.floor((a.length-1)/2)]+a[Math.floor(a.length/2)])/2 : null; };
const clock = minute => `${String(Math.floor(minute / 60)%24).padStart(2,'0')}:${String(Math.floor(minute%60)).padStart(2,'0')}${minute>=1440?' +1 day':''}`;
let transitData, selectedHub='skyway';
function renderTransit(){
 const hub=transitData.hubs.find(h=>h.id===selectedHub),day=$('day').value,[start,end]=$('window').value.split(',').map(Number);
 const events=hub.days[day].filter(e=>e[0]>=start&&e[0]<end);
 const routes=new Set(events.map(e=>e[1]));
 const weekday=hub.days['20260915'].filter(e=>e[0]>=start&&e[0]<end).length;
 const change=weekday?Math.round((events.length/weekday-1)*100):null;
 const groups={};events.forEach(e=>(groups[`${e[1]}:${e[2]}`]??=[]).push(e));
 const bins=Array(30).fill(0);events.forEach(e=>bins[Math.floor(e[0]/60)]++);const max=Math.max(1,...bins);
 $('transit-output').innerHTML=`<div class="metrics"><div class="metric"><b>${events.length}</b><span>Scheduled departures · selected window</span></div><div class="metric"><b>${routes.size}</b><span>Distinct bus routes</span></div><div class="metric"><b>${change===null?'—':`${change>0?'+':''}${change}%`}</b><span>Departures vs Tuesday · same anchor & window</span></div></div><div class="split"><div><h4>Choose a local anchor</h4><div class="hub-list">${transitData.hubs.map(h=>`<button data-hub="${h.id}" aria-pressed="${h.id===selectedHub}">${escapeText(h.name)}<small>${h.stops.length} selected stops</small></button>`).join('')}</div></div><div><h4>${escapeText(hub.name)} / departures by hour</h4><div class="chart" role="img" aria-label="Hourly departures; exact route schedules are in the table below">${bins.map((n,i)=>`<div style="height:${n/max*100}%" title="${i}:00: ${n} departures"></div>`).join('')}</div><div class="chart-labels"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>05:00 +1</span></div><p class="note">${escapeText(hub.anchor)} · ${escapeText(hub.context)}<br><a href="https://www.openstreetmap.org/?mlat=${hub.lat}&mlon=${hub.lon}#map=15/${hub.lat}/${hub.lon}" target="_blank" rel="noopener">View actual anchor location on OpenStreetMap ↗</a></p></div></div><div class="table-wrap"><table><caption class="note">Route-direction detail · times are local · gaps are schedule intervals, not predicted waits</caption><thead><tr><th>Route</th><th>Feed direction</th><th>Departures</th><th>First</th><th>Last</th><th>Median gap</th></tr></thead><tbody>${Object.values(groups).sort((a,b)=>transitData.routes[a[0][1]].name.localeCompare(transitData.routes[b[0][1]].name,undefined,{numeric:true})).map(list=>{list.sort((a,b)=>a[0]-b[0]);const route=transitData.routes[list[0][1]],gap=median(list.slice(1).map((e,i)=>e[0]-list[i][0]));return `<tr><td title="${escapeText(route.description)}"><b>${escapeText(route.name)}</b></td><td>${escapeText(list[0][2])}</td><td>${list.length}</td><td>${clock(list[0][0])}</td><td>${clock(list.at(-1)[0])}</td><td>${gap===null?'—':`${Math.round(gap)} min`}</td></tr>`;}).join('')||'<tr><td colspan="6">No scheduled departures in this window.</td></tr>'}</tbody></table></div><details><summary>Selected stops & calculation details</summary><p class="note">${hub.stops.map(s=>`${escapeText(s.id)} · ${escapeText(s.name)}`).join('<br>')}</p><p class="note">Direction 0 and 1 are GTFS identifiers, not compass directions. Each trip contributes its earliest pickup at the anchor. Full service day includes after-midnight times assigned to that service date. Retrieved ${escapeText(transitData.meta.retrievedAt)}. Feed ${escapeText(transitData.meta.feed.feed_version)}.</p></details>`;
 document.querySelectorAll('[data-hub]').forEach(b=>b.addEventListener('click',()=>{selectedHub=b.dataset.hub;renderTransit();document.querySelector(`[data-hub="${selectedHub}"]`).focus();}));
}
fetch('datasets/transit.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{transitData=data;renderTransit();['day','window'].forEach(id=>$(id).addEventListener('change',renderTransit));}).catch(()=>$('transit-output').innerHTML='<p class="error">The schedule snapshot could not load. Reload this page or use the downloadable data linked below.</p>');
